name: cubing-time-standard

services:
  api:
    build:
      context: ./server
      target: production
    restart: unless-stopped
    env_file: ./server/.env
    networks:
      - cubing-time-standard

  client:
    build:
      context: ./client
      target: production
      args:
        VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      - cubing-time-standard
    depends_on:
      - api

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - cubing-time-standard
    depends_on:
      - api
      - client

volumes:
  caddy_data:
  caddy_config:
networks:
  cubing-time-standard:
    driver: bridge
